language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install check
  - sudo pip install cpp-coveralls
script:
  - autoreconf -i && ./configure --enable-gcov && make && make check
after_success:
  - coveralls --exclude libuproc/tests --exclude libuproc/gen_codon_tables.c --exclude config.h --gcov-options '\-lp'
