language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install check
  - sudo pip install cpp-coveralls
script:
  - autoreconf -i && ./configure --enable-gcov && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
