language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install check
  - sudo pip install cpp-coveralls
script:
  - autoreconf -i && ./configure --enable-gcov && make && make check
after_success:
  - >
      coveralls
      --gcov-options '\-lp'
      --exclude common.h
      --exclude common.c
      --exclude devmode.h
      --exclude devmode.c
      --exclude ppopts.c
      --exclude main.c
      --exclude makedb.c
      --exclude import.c
      --exclude export.c
      --exclude orf.c
      --exclude libuproc/tests
      --exclude libuproc/gen_codon_tables.c
      --exclude config.h
